name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for syntax errors
      run: |
        # Find and check all JavaScript files
        echo "Checking JavaScript syntax..."
        find src -name "*.js" -type f | while read -r file; do
          echo "Checking: $file"
          node -c "$file"
        done
        
        # Also check test files
        find test -name "*.js" -type f | while read -r file; do
          echo "Checking: $file"
          node -c "$file"
        done
        
        echo "All JavaScript files have valid syntax"
        
    - name: Verify core file structure
      run: |
        # Check that core files and directories exist
        echo "Verifying core file structure..."
        
        # Core files
        for file in package.json README.md LICENSE; do
          if [ ! -f "$file" ]; then
            echo "Missing required file: $file"
            exit 1
          fi
        done
        
        # Core directories
        for dir in src src/embedded src/generators data test examples; do
          if [ ! -d "$dir" ]; then
            echo "Missing required directory: $dir"
            exit 1
          fi
        done
        
        # Essential source files
        for file in src/cli.js src/csv.js src/svg.js; do
          if [ ! -f "$file" ]; then
            echo "Missing essential file: $file"
            exit 1
          fi
        done
        
        # Check for at least one CSV file in data/
        if ! ls data/*.csv >/dev/null 2>&1; then
          echo "No CSV files found in data/ directory"
          exit 1
        fi
        
        echo "File structure check passed"
        
    - name: List JavaScript modules
      run: |
        echo "=== Source files ==="
        find src -name "*.js" -type f | sort
        
        echo -e "\n=== Test files ==="
        find test -name "*.test.js" -type f | sort
        
        echo -e "\n=== Embedded modules ==="
        find src/embedded -name "*.js" -type f | sort
        
    - name: Check package.json validity
      run: |
        # Validate package.json
        npm pkg fix --dry-run
        
        # Check that main script is executable
        if [ ! -x "src/cli.js" ]; then
          echo "src/cli.js is not executable"
          exit 1
        fi
        
        echo "Package configuration is valid"