name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for syntax errors
      run: |
        # Check JavaScript syntax
        node -c src/cli.js
        node -c src/csv.js
        node -c src/svg.js
        node -c src/charts/scatter.js
        
        echo "All JavaScript files have valid syntax"
        
    - name: Verify file structure
      run: |
        # Check that all required files exist
        test -f package.json
        test -f src/cli.js
        test -f src/csv.js
        test -f src/svg.js
        test -f src/charts/scatter.js
        test -f data/qwen30b3a_q3.csv
        test -d test/
        
        echo "File structure check passed"
        
    - name: Check package.json validity
      run: |
        # Validate package.json
        npm pkg fix --dry-run
        
        # Check that main script is executable
        test -x src/cli.js
        
        echo "Package configuration is valid"