name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Test CLI functionality
      run: |
        # Test basic help command
        node src/cli.js --help
        
        # Test chart generation with sample data
        node src/cli.js -x n_depth -y avg_ts -g model data/qwen30b3a_q3.csv -o test-output.svg
        
        # Verify SVG was created and contains expected content
        if [ ! -f test-output.svg ]; then
          echo "Error: SVG file was not created"
          exit 1
        fi
        
        if ! grep -q "<svg" test-output.svg; then
          echo "Error: Generated file does not contain SVG content"
          exit 1
        fi
        
        if ! grep -q "n_depth vs avg_ts" test-output.svg; then
          echo "Error: Generated SVG does not contain expected chart title"
          exit 1
        fi
        
        echo "CLI test passed successfully"